kafka:
  bootstrap-servers: kafka:9092
  topic:
    receiver: mail
server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: testpass
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
---
spring:
  profiles: dev

server:
  port: 8082
